### ISSUE TITLE
Incomplete Uninstallation of Microsoft Edge: Remnants Persist After Selecting Removal Options

### ISSUE THREAD

**Issue by sakshiagrwal** [he3als/EdgeRemover#1]
**I selected the following options for uninstallation:**
[1] Remove Edge
[3] Remove Edge User Data
[4] Block WebView install & Edge updates

However, after uninstallation, remnants of Microsoft Edge still persist in the system. Specifically, I've noticed some leftover entries.
**Leftover folders:**
- C:\Program Files (x86)\Microsoft\EdgeCore
- C:\Program Files (x86)\Microsoft\EdgeUpdate

**Registry entries:**
- Computer\HKEY_CLASSES_ROOT\AppID\MicrosoftEdgeUpdate.exe
- Computer\HKEY_CLASSES_ROOT\MicrosoftEdgeUpdate.CoreClass
- Computer\HKEY_CLASSES_ROOT\MicrosoftEdgeUpdate.CoreClass\CurVer
- Computer\HKEY_CLASSES_ROOT\MicrosoftEdgeUpdate.CoreClass.1... there are numerous other registry entries associated with Edge.

Additionally, in the system settings under 'Apps & Features,' the entry for **'Microsoft Edge Update'** remains present.

**Windows 10 22h2**

![Edge](https://github.com/he3als/EdgeRemover/assets/81718060/93fd4654-da5f-4f43-86eb-0761115a95f4)

**Comment by he3als** [comment]
EdgeUpdate is only uninstalled when both WebView and Edge are removed, as EdgeUpdate updates WebView.

The `[4] Block WebView install & Edge updates` option only sets policies to block Edge from updating.

I'll keep this open as I want to:
1. Make this more clear in the script
2. Investigate what the EdgeCore folder does

**Comment by gtumanyan** [comment]
On my Windows 22631.4317 after Edge removal MicrosoftEdgeUpdate.exe starts with Scheduler at log on and at 7:02 every day.
Can we disable or delete those tasks also?

**Comment by he3als** [comment]
It would be unsupported to do so as EdgeUpdate still updates WebView, which is good for compatibility, security, etc.

EdgeUpdate shouldn't take up much resources.

As a note, the WebView uninstall option had been removed from EdgeRemover for a while now because WebView is an essential dependency for some apps.
