### ISSUE TITLE
Cannot install Edge

### ISSUE THREAD

**Issue by gtumanyan** [he3als/EdgeRemover#4]
I successfully installed WebView but running **iex (&{$(irm https://raw.githubusercontent.com/he3als/EdgeRemover/main/get.ps1)} -ClearUpdateBlocks)** and selecting 
**[2] Install Edge**
results in 

> [INFO] Requesting from the Microsoft Edge Update API...
> [CRITICAL] Failed to parse Microsoft Edge from ""!
> [CRITICAL] Error: Cannot convert 'System.Object[]' to the type 'System.DateTime' required by parameter 'Date'. Specified method is not supported.
>

**Comment by he3als** [comment]
Can you run `(Invoke-WebRequest "https://edgeupdates.microsoft.com/api/products" -UseBasicParsing).Content` in PowerShell and a send a screenshot of the output please?

**Comment by he3als** [comment]
Fixed in the latest release, thank you
