### ISSUE TITLE
Apart from EdgeRemover, is there a default Windows app remover?

### ISSUE THREAD

**Issue by candrapersada** [he3als/EdgeRemover#6]

**Comment by he3als** [comment]
Run in PowerShell as an administrator

```powershell
Get-AppxPackage | ?{ !$_.NonRemovable -and !$_.IsFrameWork} | Out-GridView -PassThru | Remove-AppxPackage
```

![image](https://github.com/he3als/EdgeRemover/assets/65787561/908531a6-b040-4851-b22b-ca553ee8d6a0)

**Comment by jyxjjj** [comment]
Did `Out-GridView -PassThru` show this window in your screenshot?
Can it be filtered manually by mouse again, such as to keep something still needed, then click `OK` will run `Remove-AppXPackage`?
