### ISSUE TITLE
Arguments don't seem to be taken when running the get.ps1 from powershell

### ISSUE THREAD

**Issue by coryarobbins** [he3als/EdgeRemover#8]
I am attempting to pass -UninstallEdge and -NonInteractive to this line:
`iex (&{$(irm https://cdn.jsdelivr.net/gh/he3als/EdgeRemover@main/get.ps1)} [ARGUMENTS HERE])`

I've tried passing the arguments like this:
`iex (&{$(irm https://cdn.jsdelivr.net/gh/he3als/EdgeRemover@main/get.ps1)} [-UninstallEdge, -NonInteractive])`

`iex (&{$(irm https://cdn.jsdelivr.net/gh/he3als/EdgeRemover@main/get.ps1)} ["-UninstallEdge", "-NonInteractive"])`

`iex (&{$(irm https://cdn.jsdelivr.net/gh/he3als/EdgeRemover@main/get.ps1)} -UninstallEdge, -NonInteractive)`

`iex (&{$(irm https://cdn.jsdelivr.net/gh/he3als/EdgeRemover@main/get.ps1)} -UninstallEdge -NonInteractive)`

Regardless of how I do it, I still get the menu prompt.  I'm 100% sure I'm missing something...

**Comment by he3als** [comment]
Hi, I've fixed the snippet in the README and made minor improvements to the `get.ps1` script. I've also included an example

Thank you for reporting
