### ISSUE TITLE
Cannot Find '--force-uninstall'.

### ISSUE THREAD

**Issue by EXXodos911** [he3als/EdgeRemover#9]
![Screenshot 2024-07-22 002926](https://github.com/user-attachments/assets/a96da7bc-14f2-449a-a818-8dd6dc49a3b9)
- Using Latest EdgeRemover.ps1 Release. ( I need it as a file )
- Opened admin Powershell and ran 
```powershell -ep bypass .\RemoveEdge.ps1 -UninstallEdge -RemoveEdgeData -KeepAppX -NonInteractive```

**Comment by he3als** [comment]
- Which Windows version (e.g. 22H2) is this?
- Is Windows and Edge entirely up to date?

If not, it's okay, but I want to know how to make EdgeRemover compensate for these older builds.

> Anyone knows why would IntegratedServicesRegionPolicySet.json not be there?

It's likely due to an outdated Windows version.
